name: mobile
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  core:
    path: ../core
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  kernel:
    path: ../kernel
  get: ^4.6.1
  google_fonts: ^2.3.1
  klocalizations_flutter: ^0.0.6
  persistent_bottom_nav_bar: ^4.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
